"""Events: one frozen dataclass per kind, joined in the unions ``IncomingEvent`` and ``GeneratedEvent``."""

from dataclasses import dataclass
from enum import Enum

from account_ledger.domain.model.ids import (
    AccountId,
    AuthorizationId,
    CapitalizationId,
    Day,
    EventId,
    FeeId,
    IncomingId,
    InstalmentCount,
    InstalmentId,
    InterestId,
    RefundId,
)
from account_ledger.domain.model.money import Amount, Direction


class SettlementKind(Enum):
    """Whether a settlement is the last one against its hold (AMB-013)."""

    FINAL = "final"
    PARTIAL = "partial"


@dataclass(frozen=True, slots=True)
class Whole:
    """A credit posted as one amount."""


@dataclass(frozen=True, slots=True)
class Instalments:
    """A credit posted in parts, each an instalment event (AMB-017, AMB-020)."""

    count: InstalmentCount


type Posting = Whole | Instalments


@dataclass(frozen=True, slots=True)
class _IncomingEventBase:
    """What every incoming event holds: its ID, the day it is booked, its account, and its value date."""

    id: IncomingId
    booked: Day
    account: AccountId
    value_date: Day


@dataclass(frozen=True, slots=True)
class _GeneratedEventBase[I: (InstalmentId, FeeId, RefundId, InterestId, CapitalizationId)]:
    """What every event the ledger generates holds: its ID, of its kind's own type, its account, and its value date."""

    id: I
    account: AccountId
    value_date: Day


@dataclass(frozen=True, slots=True)
class Credit(_IncomingEventBase):
    """Money in, posted whole or in instalments."""

    amount: Amount
    posting: Posting


@dataclass(frozen=True, slots=True)
class Debit(_IncomingEventBase):
    """Money out, posted at once."""

    amount: Amount


@dataclass(frozen=True, slots=True)
class Authorization(_IncomingEventBase):
    """A request to hold an amount, approved or declined against the available balance."""

    authorization: AuthorizationId
    amount: Amount


@dataclass(frozen=True, slots=True)
class Settlement(_IncomingEventBase):
    """A settlement against an authorization's hold, final or partial (AMB-013)."""

    authorization: AuthorizationId
    amount: Amount
    kind: SettlementKind


@dataclass(frozen=True, slots=True)
class Reversal(_IncomingEventBase):
    """An undo of an earlier event, named by its ID."""

    target: EventId


type IncomingEvent = Credit | Debit | Authorization | Settlement | Reversal


@dataclass(frozen=True, slots=True)
class Instalment(_GeneratedEventBase[InstalmentId]):
    """A part of a credit in instalments, generated by the ledger with the credit's value date (AMB-017, AMB-020)."""

    amount: Amount


@dataclass(frozen=True, slots=True)
class Fee(_GeneratedEventBase[FeeId]):
    """The overdraft fee for a day that closed negative, generated at a close and value-dated that close (AMB-002)."""

    amount: Amount


@dataclass(frozen=True, slots=True)
class FeeRefund(_GeneratedEventBase[RefundId]):
    """The refund of a fee in force whose day closes at or above zero again, value-dated the close (AMB-004)."""

    fee: FeeId
    amount: Amount


@dataclass(frozen=True, slots=True)
class InterestAccrual(_GeneratedEventBase[InterestId]):
    """A day's interest, generated at its own close; its ID is for the day it is generated (AMB-005)."""

    amount: Amount

    def __post_init__(self) -> None:
        if self.id.for_day != self.id.generated_day:
            raise ValueError("an accrual is for the day it is generated; an earlier day takes an adjustment")


@dataclass(frozen=True, slots=True)
class InterestAdjustment(_GeneratedEventBase[InterestId]):
    """A correction of an earlier day's interest, generated when a changed closing is recognised (AMB-005)."""

    direction: Direction
    amount: Amount

    def __post_init__(self) -> None:
        if self.id.for_day >= self.id.generated_day:
            raise ValueError("an adjustment is for an earlier day; the day it is generated takes an accrual")


@dataclass(frozen=True, slots=True)
class Capitalization(_GeneratedEventBase[CapitalizationId]):
    """The accrued interest, credited to the ledger balance on a capitalization day (AMB-007, AMB-023)."""

    amount: Amount


type GeneratedEvent = Instalment | Fee | FeeRefund | InterestAccrual | InterestAdjustment | Capitalization
